Repository Financial-Times/o-editorial-layout, pull requests merged in 2020-08, with the labels that each got.

#21 Fix readme linting warnings
  README.md
Labels: component

#20 Correct blockquote styles within the wrapper class.
  main.scss
Labels: release:patch

#23 Add general usage to readme
  README.md
Labels: component, release:patch

#24 Use the new $default-branch macro instead of hardcoding the branch name
  .github/workflows/percy.yml
Labels: component

#25 Move to Github's native Dependabot
  .dependabot/config.yml
  .github/dependabot.yml
  .github/workflows/automerge.yml
Labels: component

#28 remove the ci section from origami.json
  origami.json
Labels: component
